# Site settings
title: Jeong Hyun Kim
email: kim1@lsu.edu
description: Assistant Professor of Political Science, Louisiana State University
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeonghkim.github.io" # the base hostname & protocol for your site
#avatar: "/img/shaun-jackman-square.jpg"
avatarurl: "https://jeonghkim.github.io/aboutme/"

# Homepage tiles
#tiles-source: posts # accepts "posts" or "pages"
#tiles-count: 3

navbar-links:
  CV: "https://jeonghyunkimcom.files.wordpress.com/2019/03/kim_cv-1.pdf"
  Research:
  About Me: "aboutme"

# Misc settings
featured-image-source:

# Social settings
#500px_url:
#facebook_url:
github_url: https://github.com/jeonghkim
email_url: kim1@lsu.edu
twitter_url: https://twitter.com/jeonghkim1


# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
